### ISSUE TITLE
Pyserial 3.0 Incompatible With Our Current Build

### ISSUE THREAD

**Issue by Kgespada** [vapor-ware/OpenDCRE#11]
The solution to this right now is to modify the Dockerfile so that it installs pyserial 2.7 instead of the latest version - at least until the pyserial bug is addressed or we figure out how to make our code work with it again.

**Comment by acencini** [comment]
pyserial/pyserial#59 - this issue may be fixed by enabling hardware flow control as a workaround with pyserial 3.0

assigning to @Kgespada to fix

**Comment by acencini** [comment]
this is resolved, pyserial has been moved up to v3.1.1, which is the current release.
