### ISSUE TITLE
Where are the sources for the Vapor_ipmi library?

### ISSUE THREAD

**Issue by cneth** [vapor-ware/OpenDCRE#21]
I've been playing around a bit with OpenDCRE against Intel's RMM4 IPMI implementation and in general, it works, but I'm not having any luck with the 'system' asset and would like to see exactly what the IPMI query is for this attribute.    

IT seems this all happens inside the vapor_ipmi library.  Is it open source as well?

Thanks,

Craig

**Comment by acencini** [comment]
Hi Craig,

Thanks for this report.  The vapor_ipmi library uses an internal implementation of raw IPMI that has been tested against a set of known BMCs (http://opendcre.readthedocs.io/en/latest/ipmi.html#tested-bmcs).  We have not yet released the source to the IPMI library, but I'd be happy to assist in seeing what is going on with your situation if you'd like.

Are you receiving an error, or just empty fields in the response?

Also, feel free to drop me an email if you'd like to chat directly - we met at MesosCon last week, and I believe you have my contact info.  Thanks for using OpenDCRE, and I look forward to providing any help you might need.

Thanks,
--andrew

**Comment by cneth** [comment]
Hi Andrew,

Ok, got it.  I just tried a quick test and the scan seems to work well, as well as reading various temps, fan_speeds, etc.    But the 'asset' call just returns bad gateway.   I tried it against the only 'system' device I saw in the scan:

      "board_id": "40000002", 
      "devices": [
        {
          "device_id": "0100", 
          "device_type": "power"
        }, 
        {
          "device_id": "0200", 
          "device_type": "system"
        }, [...]


curl localhost:5000/opendcre/1.2/asset/40000002/0200
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>

I was just trying to figure out what that might be trying to query on the other end to get this information.

Craig

**Comment by acencini** [comment]
very cool!

in ```/logs``` there should be ```opendcre_debug.log``` and also ```opendcre_daemon.log```, where there may be a message related to this.

What the IPMI library is doing in this case, to get asset information, is to read the FRU on the BMC and extract the chassis, board, and product information from the FRU.

Typically, a JSON 500 error message is returned, as opposed to a 502 error, so I suspect there may be some issue with how the FRU is being read/translated, but could be incorrect, depending on what the logs say.

**Comment by acencini** [comment]
Ah yes, I think I am familiar with this class of errors.  Some BMCs operate differently from others, so closing the IPMI session appears to have failed in this case for this particular model of BMC.  I saw something similar with an AST2400 BMC on OCP. 

If you'd like, I could post a private build with a modified IPMI module that should let you bypass this error.  Did you build your Docker container from the Dockerfile, or pull from Docker Hub?

**Comment by cneth** [comment]
I built the container myself.    I can easily rebuild it with a new IPMI module.

Craig

**Comment by acencini** [comment]
[Vapor_IPMI-2.0.linux-x86_64.tar.gz](https://github.com/vapor-ware/OpenDCRE/files/307603/Vapor_IPMI-2.0.linux-x86_64.tar.gz)

If you drop in this module in place of the former IPMI module, and build on x64 (I am assuming that is where you are running), this private build has disabled the connection close which I will attempt to debug separately.

**Comment by cneth** [comment]
Not to be a pain, but it  looks like that tarball has a MacOS binary in it...  :-)

file ./usr/local/lib/python2.7/dist-packages/vapor_ipmi.so
./usr/local/lib/python2.7/dist-packages/vapor_ipmi.so: Mach-O universal binary with 2 architectures: [x86_64: Mach-O 64-bit x86_64 bundle] [i386: Mach-O i386 bundle]

**Comment by acencini** [comment]
sorry, i should have asked which platform you are running on - linux, macos or RPI!

**Comment by acencini** [comment]
[Vapor_IPMI-2.0.linux-x86_64.tar.gz](https://github.com/vapor-ware/OpenDCRE/files/307680/Vapor_IPMI-2.0.linux-x86_64.tar.gz)

Attached is a Linux version (properly built this time).  If you would like an RPI version, I can build an armhf version.

**Comment by cneth** [comment]
Alas, same problem....

2016-06-09 18:48:35,314 - __init__:810 - Error getting IPMI asset info: Board 1073741826, Device: 512.
Traceback (most recent call last):
  File "/opendcre/opendcre_southbound/__init__.py", line 803, in asset_info
    asset_data = get_ipmi_asset_info(board_num, device_num, app.config)
  File "/opendcre/opendcre_southbound/ipmi.py", line 232, in get_ipmi_asset_info
    ip_address=bmc_info['bmc_ip'])
IpmiError: Error closing connection: Network error sending data to BMC. [198.159.200.59].

**Comment by acencini** [comment]
In the build I sent over, the only occurrence of that logging line ```Error closing connection: Network error sending data to BMC``` was removed from the vapor_ipmi module (in vapor_ipmi.get_inventory).  Did the Docker image build from cache without taking the new module?

**Comment by cneth** [comment]
I tried rebuilding with the docker --no-cache flag but that didn't help.   

md5sum on the downloaded file is:
 86f02744c997f9d605d4fe021e13b394  /Users/v625018/Downloads/Vapor_IPMI-2.0.linux-x86_64.tar.gz

Strings on the .so shows that both the "Error closing connection: %s [%s]." and the "Network error sending data to BMC." strings are in the .so.

??

**Comment by acencini** [comment]
I missed a place where that may have occurred - the good news is, I have disabled that and included one more private here.  The bad news is, it appears to be in the code path where we retrieve the FRU records, and the error message was getting stomped by the attempt to close the connection as part of cleanup.  So, this may not totally 'fix' this piece, but will help uncover what is going on for real.  

[Vapor_IPMI-2.0.linux-x86_64.tar.gz](https://github.com/vapor-ware/OpenDCRE/files/307753/Vapor_IPMI-2.0.linux-x86_64.tar.gz)

Thanks for your help in narrowing this down!

**Comment by cneth** [comment]
Ok, now I see some different behavior.  Still failing, but more info in the log:

Traceback (most recent call last):
  File "/opendcre/opendcre_southbound/__init__.py", line 803, in asset_info
    asset_data = get_ipmi_asset_info(board_num, device_num, app.config)
  File "/opendcre/opendcre_southbound/ipmi.py", line 232, in get_ipmi_asset_info
    ip_address=bmc_info['bmc_ip'])
IpmiError: Error getting inventory: Invalid payload length received on response from BMC. [198.159.200.59]

What command is it issuing?    Maybe I could try the same command with ipmitool?

**Comment by acencini** [comment]
the command being issued is "read fru data" which reads a block of data from the FRU inventory info area.

the equivalent ipmitool command would be "ipmitool fru" - it should succeed for you with ipmitool, which is more resilient to the peculiarities of a large variety of BMC IPMI quirks.

**Comment by cneth** [comment]
FWIW, here is what ipmitool fru returns for this host:

FRU Device Description : Builtin FRU Device (ID 0)
 Chassis Type          : Rack Mount Chassis
 Chassis Part Number   : ..................
 Chassis Serial        : ..................
 Chassis Extra         : ...............................
 Chassis Extra         : ...............................
 Board Mfg Date        : Thu Apr  9 00:51:00 2015
 Board Mfg             : Intel Corporation
 Board Product         : S2600TP
 Board Serial          : BQTP51400516
 Board Part Number     : H26989-251
 Product Manufacturer  : Intel Corporation
 Product Name          : S2600TP
 Product Part Number   : ..........
 Product Version       : ....................
 Product Serial        : ............
 Product Asset Tag     : ....................

FRU Device Description : Pwr Supply 1 FRU (ID 2)
 Product Manufacturer  : SAMSUNG ELECTRO-MECHANICS CO.,LTD
 Product Name          : IS162F22
 Product Part Number   : G36234-009
 Product Version       : 04A
 Product Serial        : PSSF162202ACNS1622A4SEAQ0446

FRU Device Description : Pwr Supply 2 FRU (ID 3)
 Product Manufacturer  : SAMSUNG ELECTRO-MECHANICS CO.,LTD
 Product Name          : IS162F22
 Product Part Number   : G36234-009
 Product Version       : 04A
 Product Serial        : PSSF162202ACNS1622A4SEAQ0445

FRU Device Description : HS Backplane (ID 8)
 Board Mfg Date        : Tue Nov 18 10:49:00 2014
 Board Mfg             : Intel Corporation
 Board Product         : FHW16X25HSBP12G
 Board Serial          : BQKP44640467
 Board Part Number     : H13900-450
 Board Extra           : Field not present

FRU Device Description : IO Module (ID 9)
 Board Mfg Date        : Mon Jul 20 15:15:00 2015
 Board Mfg             : Intel Corporation
 Board Product         : AXX10GBNIA
 Board Serial          : QSRU52903693
 Board Part Number     : G23589-251

**Comment by cneth** [comment]
Maybe that 'Board Extra: Field not present'?   Gotta love optional stuff. :-)

**Comment by acencini** [comment]
That is certainly a new one for me!

For my reference, what does ```ipmitool mc info``` (to get the make and model of the BMC) return?  i will see if i can get my hands on a similar unit and debug without having you go through it.

Do the chassis power commands, boot target and LED commands (via OpenDCRE) work ok?  The FRU and, to some extent, SDR stuff can be really nitpicky, but the other pieces tend to work out ok.

We largely designed OpenDCRE to abstract away the pain of IPMI.  The PLC (power line communication over bus bar) piece also removes the network/cabling aspect, and is really neat in an OCP environment.

**Comment by cneth** [comment]
ipmitool <redacted> mc info
Device ID                 : 33
Device Revision           : 1
Firmware Revision         : 1.18
IPMI Version              : 2.0
Manufacturer ID           : 343
Manufacturer Name         : Intel Corporation
Product ID                : 115 (0x0073)
Product Name              : Unknown (0x73)
Device Available          : yes
Provides Device SDRs      : no
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    IPMB Event Generator
    Chassis Device
Aux Firmware Rev Info     : 
    0x01
    0x06
    0xb1
    0x1d

--------------
Chassis power off/on/status all work fine (see below about 'cycle').    I didn't try the boot target as that one is a bit disruptive to test.  As for the led:   None of the returned devices in the scan identified as 'led'.   But.. If I query the system device about the led I get back some status:

curl localhost:5000/opendcre/1.2/led/40000003/0200
{
  "led_color": "unknown", 
  "led_state": "on"
}

And I can turn it on/off from that device.  (Well, at least the Intel Web page seems to think the light is on)
 
power...'cycle' returned a bad gateway and left this in the log:

2016-06-09 20:11:00,038 - __init__:686 - Error controlling IPMI power: Board 1073741827, Device: 256, Action: cycle.
Traceback (most recent call last):
  File "/opendcre/opendcre_southbound/__init__.py", line 670, in power_control
    power_status = control_ipmi_power(board_num, device_num, power_action, app.config)
  File "/opendcre/opendcre_southbound/ipmi.py", line 202, in control_ipmi_power
    ip_address=bmc_info['bmc_ip'], command=power_action)
ValueError: Invalid command provided: (cycle) [198.159.202.26].

**Comment by acencini** [comment]
i've raised related issues #23 (power cycle) and #22 (led) related to your observations

For the power cycle issue, it is likely that we intended to surface an error since there is no 'equivalent' IPMI chassis "cycle" command; however, it's easy enough to simply issue a 'power off' then 'power on' command from the Python side.

For the LED issue, that is an omission in the model that should be fixed.  I'm glad you were able to confirm that the routing you did use does indeed get reflected (at least virtually).  We will add the LED device to IPMI boards with the fix for that issue.

The other thing I am realizing, which just bit us recently, was the presence of the 502 errors from OpenDCRE - as it turns out, a new release of flask was released recently, which breaks custom error handling routines (pallets/flask#1837).  In the interim, I will update the Dockerfile to use Flask==0.10.1 to ensure it's easier to get error messages without having to resort to the logs.  I've logged issue #24 for that :)

For the asset information, that will take a bit more work to track down on my side.  In an upcoming release, there is a good chance we will refresh the IPMI back-end to OpenDCRE significantly to use a more common component such as OpenIPMI rather than relying on a patchwork of BMC support.

Thank you very much for raising this issue!

**Comment by acencini** [comment]
There is a new build of OpenDCRE v1.2.2 in branch v1.2.2 that should address the issues above - please let me know if it works for you - the changes are for x64 only - we have not verified this on RPI or made the needed Dockerfile changes for that yet.  Thanks!

**Comment by cneth** [comment]
I can confirm that the V1.2.2 code resolves the asset issue.  Now I get:

$ curl localhost:5000/opendcre/1.2/asset/40000002/0200
{
  "bmc_ip": "198.xx.xx.xx", 
  "board_info": {
    "manufacturer": "Intel Corporation", 
    "part_number": "", 
    "product_name": "S2600TP", 
    "serial_number": "BQTP51400516"
  }, 
  "chassis_info": {
    "chassis_type": "Rack Mount Chassis", 
    "part_number": "..................", 
    "serial_number": ".................."
  }, 
  "product_info": {
    "asset_tag": "....................", 
    "manufacturer": "Intel Corporation", 
    "part_number": "..........", 
    "product_name": "S2600TP", 
    "serial_number": "............", 
    "version": "...................."
  }
}

This matches what IPMItool returns for the main FRU.    I can also report that the led device shows up and works now.  I have not tried the power 'cycle' command yet.

Craig

**Comment by acencini** [comment]
This is fantastic news, thanks so much for trying this out, @cneth :)

**Comment by acencini** [comment]
in v1.3.0, OpenDCRE has migrated to using pyghmi (https://github.com/openstack/pyghmi) for its IPMI back-end.  hope this helps resolve this issue :)
